lib/coliving_web/router.ex
defmodule ColivingWeb.Router do
  use ColivingWeb, :router

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ColivingWeb.Plugs.SessionPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_only do
    plug ColivingWeb.Plugs.SessionPlug
    plug ColivingWeb.Plugs.AuthPlug
  end

  scope "/", ColivingWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/privacy", PageController, :privacy
  end

  scope "/", ColivingWeb do
    pipe_through [:browser, :admin_only]

    resources "/rooms", RoomController
    live_dashboard "/dashboard", metrics: ColivingWeb.Telemetry
  end

  scope "/", ColivingWeb do
    pipe_through :api
    get "/config.json", ConfigController, :index
  end

  scope "/session", ColivingWeb do
    pipe_through :browser
    get "/", SessionController, :index
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", ColivingWeb do
  #   pipe_through :api
  # end
end

lib/coliving_web/views/layout_view.ex
defmodule ColivingWeb.LayoutView do
  use ColivingWeb, :view
end

lib/coliving_web/templates/layout/_footer.html.eex
<hr>
<footer class="footer">
  <a href="<%= Routes.page_path(@conn, :privacy) %>">Privacy Policy</a>
</footer>

lib/coliving_web/templates/layout/_footer.html.heex
<hr />
<footer class="footer">
  <a href={ Routes.page_path(@conn, :privacy) }>Privacy Policy</a>
</footer>

lib/coliving_web/templates/layout/_navigation.html.eex
<header>
  <section class="container">
    <nav role="navigation">
      <ul>
      <%= if @conn.assigns[:logged_in] do %>
        <li>
            <a href="<%= Routes.room_path(@conn, :index) %>">Room Management</a>
        </li>

        <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
        <li>
          <a href="<%= Routes.live_dashboard_path(@conn, :home) %>" target="_blank">Live Dashboard</a>
        </li>
        <% end %>

        <li>
            <a href="<%= Routes.session_path(@conn, :logout) %>">Logout</a>
        </li>

      <% else %>
        <li>
          <a href="<%= Routes.session_path(@conn, :index) %>">Management</a>
        </li>
      <% end %>
      
      </ul>
    </nav>
    <a href="<%= Routes.page_path(@conn, :index) %>" class="phx-logo">
      <h3><%= Application.get_env(:coliving, :app_title) %></h3>
    </a>
  </section>
</header>

lib/coliving_web/templates/layout/_navigation.html.heex
<header>
  <section class="container">
    <nav role="navigation">
      <ul>
        <%= if @conn.assigns[:logged_in] do %>
        <li>
          <a href={ Routes.room_path(@conn, :index) }>Room Management</a>
        </li>

        <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
        <li>
          <a href={ Routes.live_dashboard_path(@conn, :home) } target="_blank">Live Dashboard</a>
        </li>
        <% end %>

        <li>
          <a href={ Routes.session_path(@conn, :logout) }>Logout</a>
        </li>
        <% else %>
        <li>
          <a href={ Routes.session_path(@conn, :index) }>Management</a>
        </li>
        <% end %>
      </ul>
    </nav>
    <a href={ Routes.page_path(@conn, :index) } class="phx-logo">
      <h3><%= Application.get_env(:coliving, :app_title) %></h3>
    </a>
  </section>
</header>

lib/coliving_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || Application.get_env(:coliving, :app_title) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <%= render ColivingWeb.LayoutView, "_navigation.html", conn: @conn %>

    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    
    <%= render ColivingWeb.LayoutView, "_footer.html", conn: @conn %>

    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
    <script>
      connectToSocket();
    </script>
  </body>
</html>

lib/coliving_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || Application.get_env(:coliving, :app_title) %></title>
    <link rel="stylesheet" href={ Routes.static_path(@conn, "/css/app.css") }/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <%= render ColivingWeb.LayoutView, "_navigation.html", conn: @conn %>

    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    
    <%= render ColivingWeb.LayoutView, "_footer.html", conn: @conn %>

    <script type="text/javascript" src={ Routes.static_path(@conn, "/js/app.js") }></script>
    <script>
      connectToSocket();
    </script>
  </body>
</html>

lib/coliving_web/templates/layout/clean.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || Application.get_env(:coliving, :app_title) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <a href="#" class="phx-logo">
          <h2><%= assigns[:page_title] || Application.get_env(:coliving, :app_title) %></h2>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/coliving_web/templates/layout/clean.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || Application.get_env(:coliving, :app_title) %></title>
    <link rel="stylesheet" href={ Routes.static_path(@conn, "/css/app.css") }/>
  </head>
  <body>
    <header>
      <section class="container">
        <a href="#" class="phx-logo">
          <h2><%= assigns[:page_title] || Application.get_env(:coliving, :app_title) %></h2>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <%= @inner_content %>
    </main>
  </body>
</html>